#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class ThriftEvent
  include ::Thrift::Struct, ::Thrift::Struct_Union
  TIMESTAMP = 1
  VERSION = 2
  HOST = 3
  MESSAGE = 4

  FIELDS = {
    TIMESTAMP => {:type => ::Thrift::Types::STRING, :name => 'timestamp'},
    VERSION => {:type => ::Thrift::Types::STRING, :name => 'version'},
    HOST => {:type => ::Thrift::Types::STRING, :name => 'host', :optional => true},
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field timestamp is unset!') unless @timestamp
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field version is unset!') unless @version
  end

  ::Thrift::Struct.generate_accessors self
end

